# 워크플로의 이름 지정
name : CI

# 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3
          # uses 키워드는 지정한 리포지토리를 확인하고 코드에 대한 작업을 실행함
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew # 스텝의 이름을 지정
        run: chmod +x gradlew
        # run은 실행할 명령어를 입력

      - name: Build with Gradle
        run: ./gradlew clean build
        # ./gradlew clean build에는 그레들을 사용해 프로젝트를 빌드 이전 상태로 돌리고 다시 빌드하는 명령어를 실행